name: urawai_pos
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  uuid: ^2.0.4
  provider: ^4.0.4
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  connectivity: ^0.4.8+5
  date_range_picker: ^1.0.5
  image_picker: ^0.6.3+1
  firebase_storage: ^3.0.0
  flutter_image_compress: ^0.6.5+1
  shimmer: ^1.1.1
  shared_preferences: ^0.5.7+3
  email_validator: ^1.0.4
  get_it: ^4.0.2
  charts_flutter: ^0.9.0
  flutter_phoenix: ^0.1.0
  
  #send email 
  flutter_email_sender: ^3.0.1
  

  #image slider
  carousel_slider: ^2.2.1

  #Animations
  animations: ^1.1.1
<<<<<<< HEAD


=======
  animated_text_kit: ^2.2.0
>>>>>>> fad176828588cf8752bc406579b8cff33c2eba72
  
  #export to CSV
  csv: ^4.0.3

  #Printer Bluetooth
  esc_pos_bluetooth: ^0.2.8
  esc_pos_utils: ^0.3.6
  flutter_bluetooth_basic: ^0.1.5

  #Open Setting Page
  app_settings: ^4.0.0

  #responsive ui
  responsive_builder: ^0.2.0+2

  #auto Text
  auto_size_text: ^2.1.0

  device_preview: ^0.4.5

  #Animation Floating button for Mobile UI
  animated_floatactionbuttons: ^0.1.0

  #validator Number
  validators: ^2.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
<<<<<<< HEAD


   
=======
  #  - assets/images/chef-hat.png
  #  - assets/images/bakmi_ayam_spesial.png
  #  - assets/images/bakmi_ayam_pedas.jpg
  #  - assets/images/bakso.jpg
  #  - assets/images/nasi_goreng.jpg
  #  - assets/images/eskopi_susu.jpg
  #  - assets/images/pizza_cheese.png
  #  - assets/images/noimage.png
  #  - assets/images/placeholder.gif
  #  - assets/images/login_image.jpg
  #  - assets/images/logo.png
  #  - assets/images/rabbit_black.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
>>>>>>> fad176828588cf8752bc406579b8cff33c2eba72
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
